PROGRAM=multicast

#EXTRA_CFLAGS+=-I../esp-gdbstub/include
#EXTRA_LDFLAGS+=-L../esp-gdbstub/lib
#CFLAGS+=-DportREMOVE_STATIC_QUALIFIER -DINCLUDE_pcTaskGetTaskName=1 -std=c99
#EXTRA_COMPONENTS = extras/softuart
EXTRA_COMPONENTS = extras/dhcpserver extras/http-parser extras/esp-wifi-config
include ../common.mk
#LIBS+=esp-gdbstub
#PROGRAM_CFLAGS+=-O0
